# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-31 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0009_auto_20161031_1032'),
        ('catalogue', '0009_slugfield_noop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='conf',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='confs.Conference'),
        ),
    ]
