# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-31 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_product_conf'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
