# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-10 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_product_for_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clarity_rating',
            field=models.SmallIntegerField(default=0, verbose_name='Clarté du dossier'),
        ),
        migrations.AddField(
            model_name='product',
            name='correction_rating',
            field=models.SmallIntegerField(default=0, verbose_name='Qualité de la correction'),
        ),
        migrations.AddField(
            model_name='product',
            name='difficulty_rating',
            field=models.SmallIntegerField(default=0, verbose_name='Difficulté du dossier'),
        ),
        migrations.AddField(
            model_name='product',
            name='interest_rating',
            field=models.SmallIntegerField(default=0, verbose_name='Intérêt global du dossier'),
        ),
    ]
