# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-16 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_auto_20170110_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='difficulty_rating',
            field=models.SmallIntegerField(default=6, verbose_name='Difficulté du dossier'),
        ),
    ]
