# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20180716_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='conf',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='confs.Conference'),
        ),
    ]
