version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}
  solr_data_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    env_file: .env-dev

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: python /app/manage.py runserver_plus 0.0.0.0:8000
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=blousebrothers
      - USE_DOCKER=yes
      - VIRTUAL_HOST=futur.blousebrothers.fr
      - LETSENCRYPT_HOST=futur.blousebrothers.fr
      - LETSENCRYPT_EMAIL=julien.almarcha@labresult.fr
    volumes:
      - .:/app
    expose:
      - 8000
    links:
      - postgres
      - solr

  solr:
    build: ./compose/solr
    ports:
        - "8983:8983"
    volumes:
        - solr_data_dev:/opt/solr/server/solr/mycores/mycore/data
    entrypoint:
        - docker-entrypoint.sh
        - solr-precreate
        - mycore

networks:
  default:
    external:
      name: nginx-proxy
