version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    env_file: .env-dev

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: python /app/manage.py runserver_plus 0.0.0.0:8000
    depends_on:
      - postgres
    env_file: .env-dev
    environment:
      - POSTGRES_USER=blousebrothers
      - USE_DOCKER=yes
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "8888:8888"
    links:
      - postgres
      - solr

  solr:
    image: solr:6
    ports:
        - "8983:8983"
    volumes:
        - ./solr_cfg/:/opt/solr/server/solr/mycores
    entrypoint:
        - docker-entrypoint.sh
        - solr-precreate
        - mycore



