version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  solr_data: {}
  production_traefik: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - postgres
      - redis
      - solr
    command: /gunicorn.sh
    env_file: .env

  traefik:
    build:
      context: .
      dockerfile: ./compose/traefik/Dockerfile
    image: blousebrothers_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  redis:
    image: redis:latest

  solr:
    build: ./compose/solr
    volumes:
      - solr_data:/opt/solr/server/solr/mycores/data
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore

