#!/bin/bash
./reset_initial_migration
docker-compose run postgres dropdb -U postgres blousebrothers
docker-compose run postgres createdb -U postgres blousebrothers
docker-compose run django python manage.py migrate -v 3
docker-compose run django python manage.py loaddata --verbosity=2 all
docker-compose run django python manage.py loaddata --verbosity=2 socialaccount
