#!/bin/bash
rm blousebrothers/users/migrations/*
rm blousebrothers/confs/migrations/*
docker-compose run -u root django python manage.py makemigrations users
docker-compose run -u root django python manage.py makemigrations confs
