# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-31 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161009_0739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['name']},
        ),
    ]
