# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161031_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.CharField(choices=[(None, '---'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('INTERNE', 'Interne'), ('MEDECIN', 'Médecin')], default=None, max_length=10, null=True, verbose_name='Niveau'),
        ),
    ]
