# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20161107_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_of_residence',
            field=django_countries.fields.CountryField(default='FR', max_length=2, verbose_name='Pays de résidence'),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=django_countries.fields.CountryField(default='FR', max_length=2, verbose_name='Nationalité'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Date de naissance'),
        ),
    ]
