# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_permission_to_conferenciers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Important si vous êtes conférencier', null=True, verbose_name='Bio visible par les utilisateurs'),
        ),
        migrations.AddField(
            model_name='user',
            name='speciality',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Spécialité'),
        ),
    ]
