# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170102_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Important si tu es conférencier !', null=True, verbose_name='Bio visible par les utilisateurs'),
        ),
    ]
