# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-18 07:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='address1',
            field=models.CharField(max_length=50, null=True, verbose_name='Adresse 1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.CharField(max_length=20, null=True, verbose_name='Code postal'),
        ),
    ]
