# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-11 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20170318_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='registered', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='status_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
