# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-12 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('users', '0015_auto_20170705_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cards',
            field=models.ManyToManyField(related_name='students', through='cards.Deck', to='cards.Card'),
        ),
        migrations.AlterField(
            model_name='user',
            name='conf_encours_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='conf_entam_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='conf_pub_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
