# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-06 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20170705_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='conf_encours_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='conf_entam_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='conf_pub_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
