# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-15 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20170806_0549'),
        ('users', '0017_user_cards'),
    ]

    operations = [
    ]
