# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-28 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_set_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_dossier_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
