# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-25 08:58
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import F


def init_last_last_login(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.update(last_last_login=F('last_login'))


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_last_dossier_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_last_login',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RunPython(init_last_last_login),
    ]
