# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-21 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_friendshiprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendshiprequest',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
