# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-25 10:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
        ('users', '0020_remove_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', through='friends.Relationship', to=settings.AUTH_USER_MODEL),
        ),
    ]
