# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_update_email_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='clarity_score',
            field=models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Clarté du dossier'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='correction_score',
            field=models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Qualité de la correction'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='difficulty_score',
            field=models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, verbose_name='Difficulté du dossier'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='interest_score',
            field=models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Intérêt global du dossier'),
        ),
    ]
