# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-18 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import oscar.apps.catalogue.reviews.utils


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20170109_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Requires moderation'), (1, 'Approved'), (2, 'Rejected')], default=oscar.apps.catalogue.reviews.utils.get_default_review_status, verbose_name='Status'),
        ),
    ]
