# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-28 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import oscar.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20170318_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='body',
            field=models.TextField(blank=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='title',
            field=models.CharField(blank=True, max_length=255, validators=[oscar.core.validators.non_whitespace], verbose_name='Title'),
        ),
    ]
