# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-14 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20170726_1357'),
        ('reviews', '0005_auto_20170628_0908'),
    ]

    operations = [
    ]
