# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ziw',
            field=models.BooleanField(default=False, verbose_name='Zéro si erreur'),
        ),
        migrations.AddField(
            model_name='question',
            name='coefficient',
            field=models.PositiveIntegerField(default=1, verbose_name='Coéfficient'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Proposition'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='explaination',
            field=models.TextField(blank=True, null=True, verbose_name='Explication'),
        ),
    ]
