# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 13:15
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0003_auto_20161009_0739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='conference',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(100)], verbose_name='Prix de vente'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='items',
            field=models.ManyToManyField(help_text='Ne sélectionner que les items abordés de manière <strong>significative</strong> dans votre dossier', related_name='conferences', to='confs.Item', verbose_name='Items'),
        ),
    ]
