# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 21:53
from __future__ import unicode_literals

import blousebrothers.confs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0006_auto_20161025_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='slug',
            field=blousebrothers.confs.models.AutoSlugField(editable=False, max_length=128, populate_from='title', unique=True, verbose_name='Slug'),
        ),
    ]
