# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-31 10:32
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0008_auto_20161029_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(100)], verbose_name='Prix de vente'),
        ),
    ]
