# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 09:40
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0011_auto_20161107_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='', max_digits=6, verbose_name='Prix de vente'),
        ),
        migrations.AlterField(
            model_name='test',
            name='date_finished',
            field=models.DateTimeField(null=True, verbose_name='Fin du test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_taken',
            field=models.TimeField(null=True, verbose_name='Temps passé'),
        ),
    ]
