# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 10:27
from __future__ import unicode_literals

import blousebrothers.confs.models
from decimal import Decimal
from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0013_auto_20161120_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='explaination_image',
            field=image_cropping.fields.ImageCropField(blank=True, max_length=255, null=True, upload_to=blousebrothers.confs.models.answer_image_directory_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='', max_digits=6, verbose_name='Prix de vente'),
        ),
        migrations.AlterField(
            model_name='conferenceimage',
            name='image',
            field=image_cropping.fields.ImageCropField(max_length=255, upload_to=blousebrothers.confs.models.conf_directory_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='questionimage',
            name='image',
            field=image_cropping.fields.ImageCropField(max_length=255, upload_to=blousebrothers.confs.models.question_image_directory_path, verbose_name='Image'),
        ),
    ]
