# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 10:36
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0014_auto_20161120_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='items',
            field=models.ManyToManyField(blank=True, help_text='Ne sélectionner que les items abordés de manière <strong>significative</strong> dans votre dossier', related_name='conferences', to='confs.Item', verbose_name='Items'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='', max_digits=6, verbose_name='Prix de vente'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='specialities',
            field=models.ManyToManyField(blank=True, related_name='conferences', to='confs.Speciality', verbose_name='Spécialités'),
        ),
    ]
