# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 14:08
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0015_auto_20161120_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='date_tuto',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Accès gratuit aux étudiants de ma ville le '),
        ),
        migrations.AlterField(
            model_name='conference',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='', max_digits=6, verbose_name='Prix de vente'),
        ),
    ]
