# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-29 09:28
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0018_auto_20161121_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testanswer',
            name='time_taken',
        ),
        migrations.AlterField(
            model_name='conference',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='', max_digits=6, verbose_name='Prix de vente'),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='given_answers',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.int_list_validator], verbose_name='Réponses'),
        ),
    ]
