# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-29 09:28
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0019_auto_20161129_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanswer',
            name='time_taken',
            field=models.TimeField(null=True, verbose_name='Temps passé'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='', max_digits=6, verbose_name='Prix de vente'),
        ),
    ]
