# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 14:38
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0020_auto_20161129_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='date_finished',
        ),
        migrations.RemoveField(
            model_name='test',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='testanswer',
            name='date_finished',
        ),
        migrations.RemoveField(
            model_name='testanswer',
            name='date_started',
        ),
        migrations.AddField(
            model_name='testanswer',
            name='fatals',
            field=models.ManyToManyField(to='confs.Answer', verbose_name='Erreurs graves'),
        ),
        migrations.AddField(
            model_name='testanswer',
            name='nb_errors',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'erreurs"),
        ),
        migrations.AlterField(
            model_name='conference',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='', max_digits=6, verbose_name='Prix de vente'),
        ),
        migrations.AlterField(
            model_name='test',
            name='score',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Résultat'),
        ),
    ]
