# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-09 16:19
from __future__ import unicode_literals

import blousebrothers.confs.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0026_create_test_for_conferenciers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', image_cropping.fields.ImageCropField(max_length=255, upload_to=blousebrothers.confs.models.answer_image_directory_path, verbose_name='Image')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Libellé')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='explaination',
            field=models.TextField(blank=True, null=True, verbose_name='Remarque globale pour la correction'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='explaination_image',
            field=image_cropping.fields.ImageCropField(blank=True, max_length=255, null=True, upload_to=blousebrothers.confs.models.answer_image_directory_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='', max_digits=6, verbose_name='Prix de vente'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(verbose_name='Enoncé'),
        ),
        migrations.AddField(
            model_name='answerimage',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='confs.Answer'),
        ),
    ]
