# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-21 15:48
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0031_auto_20161221_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='', max_digits=6, verbose_name='Prix de vente'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_over',
            field=models.DateField(verbose_name='Date created'),
        ),
    ]
