# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-24 15:48
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0039_auto_20170123_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='result',
        ),
        migrations.AlterField(
            model_name='conference',
            name='for_sale',
            field=models.BooleanField(default=False, help_text="Publier mon dossier avec les paramètres sélectionnés. Je certifie que le matériel de ma conférence est original et je dégage BlouseBrothers de toute responsabilité concernant son contenu. Je suis au courant de mes obligations en matière de fiscalité, détaillées dans les <a href='/cgu/'>conditions générales d'utilisation</a>.", verbose_name='Publier'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='', max_digits=6, verbose_name='Prix de vente'),
        ),
    ]
