# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-02 09:01
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0040_auto_20170124_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='bonus_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Montant crédit wallet'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='', max_digits=6, verbose_name='Prix de vente'),
        ),
    ]
