# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-06 08:55
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_auto_20170110_1100'),
        ('confs', '0042_auto_20170202_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='product',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='catalogue.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conference',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='', max_digits=6, verbose_name='Prix de vente'),
        ),
    ]
