# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-07 16:03
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0045_auto_20170206_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='bonus_sponsor_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conference',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='', max_digits=6, verbose_name='Prix de vente'),
        ),
    ]
