# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-08 10:29
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0046_auto_20170207_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='no_fees',
            field=models.BooleanField(default=False, verbose_name='Pas de frais'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimée'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='', max_digits=6, verbose_name='Prix de vente'),
        ),
    ]
