# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-18 07:27
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0048_update_nofees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerimage',
            name='caption',
            field=models.CharField(blank=True, max_length=500, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='', max_digits=6, verbose_name='Prix de vente'),
        ),
        migrations.AlterField(
            model_name='conferenceimage',
            name='caption',
            field=models.CharField(blank=True, max_length=500, verbose_name='Légende'),
        ),
        migrations.AlterField(
            model_name='questionexplainationimage',
            name='caption',
            field=models.CharField(blank=True, max_length=500, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='questionimage',
            name='caption',
            field=models.CharField(blank=True, max_length=500, verbose_name='Libellé'),
        ),
    ]
