# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-21 08:38
from __future__ import unicode_literals

import blousebrothers.confs.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('confs', '0049_auto_20170318_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nom')),
                ('version', models.CharField(max_length=64, verbose_name='Version')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date created')),
                ('classifier', models.FileField(upload_to=blousebrothers.confs.models.classifier_directory_path, verbose_name='Classifier')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='confs.Classifier')),
                ('items', models.ManyToManyField(blank=True, related_name='prediction', to='confs.Item', verbose_name='Items')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.NullBooleanField(default=None)),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date created')),
                ('date_modified', models.DateField(auto_now=True, verbose_name='Date modified')),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_validation', to='confs.Prediction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_validation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Moyenne')),
                ('median', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Médianne')),
                ('std_dev', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Écart-type')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='confs.Item')),
            ],
        ),
        migrations.CreateModel(
            name='StatsSpe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Moyenne')),
                ('median', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Médianne')),
                ('std_dev', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Écart-type')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='confs.Speciality')),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='testanswer',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='testanswer',
            name='score',
        ),
        migrations.AddField(
            model_name='conference',
            name='average',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Score moyen'),
        ),
        migrations.AddField(
            model_name='conference',
            name='median',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Médiane'),
        ),
        migrations.AddField(
            model_name='conference',
            name='standard_deviation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Ecart-type'),
        ),
        migrations.AddField(
            model_name='question',
            name='items',
            field=models.ManyToManyField(blank=True, help_text='Ne sélectionner que les items abordés de manière <strong>significative</strong> dans votre dossier', related_name='questions', to='confs.Item', verbose_name='Items'),
        ),
        migrations.AddField(
            model_name='question',
            name='specialities',
            field=models.ManyToManyField(blank=True, related_name='questions', to='confs.Speciality', verbose_name='Spécialités'),
        ),
        migrations.AddField(
            model_name='test',
            name='max_point',
            field=models.PositiveIntegerField(default=0, verbose_name='Point'),
        ),
        migrations.AddField(
            model_name='test',
            name='point',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Point'),
        ),
        migrations.AddField(
            model_name='testanswer',
            name='max_point',
            field=models.PositiveIntegerField(default=0, verbose_name='Point'),
        ),
        migrations.AddField(
            model_name='testanswer',
            name='point',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Point'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='for_sale',
            field=models.BooleanField(default=True, help_text="Publier mon dossier avec les paramètres sélectionnés. Je certifie que le matériel de ma conférence est original et je dégage BlouseBrothers de toute responsabilité concernant son contenu. Je suis au courant de mes obligations en matière de fiscalité, détaillées dans les <a href='/cgu/'>conditions générales d'utilisation</a>.", verbose_name='Publier'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='', max_digits=6, verbose_name='Prix de vente'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='confs.Question'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='specialities',
            field=models.ManyToManyField(blank=True, related_name='prediction', to='confs.Speciality', verbose_name='Spécialités'),
        ),
    ]
