# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-26 13:57
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('confs', '0049_auto_20170318_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nom')),
                ('version', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Version')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date created')),
                ('classifier', models.FileField(upload_to='', verbose_name='un chemin ici')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='confs.Classifier')),
                ('items', models.ManyToManyField(blank=True, related_name='prediction', to='confs.Item', verbose_name='Items')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=None)),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date created')),
                ('date_modified', models.DateField(auto_now=True, verbose_name='Date modified')),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_validation', to='confs.Prediction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_validation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='items',
            field=models.ManyToManyField(blank=True, help_text='Ne sélectionner que les items abordés de manière <strong>significative</strong> dans votre dossier', related_name='questions', to='confs.Item', verbose_name='Items'),
        ),
        migrations.AddField(
            model_name='question',
            name='specialities',
            field=models.ManyToManyField(blank=True, related_name='questions', to='confs.Speciality', verbose_name='Spécialités'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='', max_digits=6, verbose_name='Prix de vente'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='confs.Question'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='specialities',
            field=models.ManyToManyField(blank=True, related_name='prediction', to='confs.Speciality', verbose_name='Spécialités'),
        ),
    ]
