# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-07 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0050_auto_20170712_1345'),
        ('confs', '0050_auto_20170806_0549'),
    ]

    operations = [
    ]
