# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-27 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0051_auto_20170727_0806'),
        ('confs', '0050_auto_20170712_1345'),
    ]

    operations = [
    ]
