# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-05 10:48
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0051_update_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='other_names',
            field=models.TextField(blank=True, null=True, verbose_name='Autres noms (séparés par des virgules)'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='', max_digits=6, verbose_name='Prix de vente'),
        ),
    ]
