# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-08 09:51
from __future__ import unicode_literals

from django.db import migrations
from csv import DictReader


def create_voucher_codes(apps, schema_editor):
    """ Create test for conferencier to be able to test their own confs"""
    Voucher = apps.get_model('voucher', 'Voucher')
    model = Voucher.objects.get(name="CODE_20_PERCENT")
    offer = model.offers.first()
    with open('codes_promo/Conferenciers.csv') as f:
        csv_conf = DictReader(f)
        for row in csv_conf:
            voucher = Voucher.objects.create(
                    name='CONFERENCIER_' + row['NOM'],
                    code=row['CODE'],
                    usage=model.usage,
                    start_datetime=model.start_datetime,
                    end_datetime=model.end_datetime,
                )
            voucher.offers.add(offer)
    with open('codes_promo/Assos.csv') as f:
        csv_asso = DictReader(f)
        for row in csv_asso:
            voucher = Voucher.objects.create(
                    name='CORPO_' + row['ABREV'],
                    code=row['CODE_CORP'],
                    usage=model.usage,
                    start_datetime=model.start_datetime,
                    end_datetime=model.end_datetime,
                )
            voucher.offers.add(offer)


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0052_auto_20170905_1048'),
    ]

    operations = [
        migrations.RunPython(create_voucher_codes),
    ]
