# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-27 15:15
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0052_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='', max_digits=6, verbose_name='Prix de vente'),
        ),
        migrations.AlterField(
            model_name='predictionvalidation',
            name='valid',
            field=models.NullBooleanField(default=None),
        ),
    ]
