# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-08 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0051_merge'),
        ('confs', '0054_auto_20170808_0852'),
    ]

    operations = [
    ]
