# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-16 08:54
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0054_delete_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='for_share',
            field=models.BooleanField(default=True, help_text="Le dossier est accessible aux personnes autorisées dans la section<a href='/amis'>Amis</a>.", verbose_name='Partager avec mes élèves / amis'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='', max_digits=6, verbose_name='Prix de vente'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_over',
            field=models.DateField(verbose_name="Valide jusqu'au"),
        ),
    ]
