# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-14 10:28
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0055_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='testanswer',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='testanswer',
            name='score',
        ),
        migrations.AddField(
            model_name='test',
            name='max_point',
            field=models.PositiveIntegerField(default=0, verbose_name='Point'),
        ),
        migrations.AddField(
            model_name='test',
            name='point',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Point'),
        ),
        migrations.AddField(
            model_name='testanswer',
            name='max_point',
            field=models.PositiveIntegerField(default=0, verbose_name='Point'),
        ),
        migrations.AddField(
            model_name='testanswer',
            name='point',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Point'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='', max_digits=6, verbose_name='Prix de vente'),
        ),
    ]
