# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-16 10:38
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0056_auto_20170814_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Moyenne')),
                ('median', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Médianne')),
                ('std_dev', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Écart-type')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='confs.Item')),
            ],
        ),
        migrations.CreateModel(
            name='StatsSpe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Moyenne')),
                ('median', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Médianne')),
                ('std_dev', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Écart-type')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='confs.Speciality')),
            ],
        ),
        migrations.AlterField(
            model_name='conference',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='', max_digits=6, verbose_name='Prix de vente'),
        ),
    ]
