FROM python:3.5

ENV PYTHONUNBUFFERED 1

# extra dev tools
RUN apt-get update
RUN apt-get install -y gettext
RUN apt-get install -y --force-yes graphviz
# Requirements have to be pulled and installed here, otherwise caching won't work
COPY ./requirements /requirements
RUN pip install -r /requirements/local.txt
RUN easy_install  /requirements/django_django_csv_exports-1.0.0-py3.5.egg
COPY ./i18n_oscar/locale/fr/LC_MESSAGES/django.* /usr/local/lib/python3.5/site-packages/oscar/locale/fr/LC_MESSAGES/

COPY ./compose/django/entrypoint.sh /entrypoint.sh
RUN sed -i 's/\r//' /entrypoint.sh
RUN chmod +x /entrypoint.sh
RUN groupadd -r django && useradd -d /app -g django django

WORKDIR /app

ENTRYPOINT ["/entrypoint.sh"]
