# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-02 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangopay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangopaywallet',
            name='description',
            field=models.CharField(default='EUR', max_length=128),
        ),
    ]
