# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangopay', '0004_auto_20170628_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangopaycardregistration',
            name='mangopay_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mangopay_card_registration', to='mangopay.MangoPayCard'),
        ),
        migrations.AlterField(
            model_name='mangopaypayin',
            name='mangopay_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mangopay_payins', to='mangopay.MangoPayCard'),
        ),
    ]
