# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-29 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='share_confs',
            field=models.BooleanField(default=True),
        ),
    ]
