# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-24 16:28
from __future__ import unicode_literals

import blousebrothers.friends.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_friends'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0002_relationship_share_confs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tu peux par exemple entrer le nom de ta corpo :)', max_length=512, unique=True, verbose_name='Nom du groupe')),
                ('avatar', image_cropping.fields.ImageCropField(max_length=255, null=True, upload_to=blousebrothers.friends.models.group_avatar_path, verbose_name='Avatar')),
                ('cropping', image_cropping.fields.ImageRatioField('avatar', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('members', models.ManyToManyField(related_name='bbgroups', to=settings.AUTH_USER_MODEL)),
                ('moderators', models.ManyToManyField(related_name='groups_moderator', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.University', verbose_name='Ville')),
            ],
        ),
        migrations.CreateModel(
            name='GroupInvitRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_users', to='friends.Group')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_invits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberShipRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to='friends.Group')),
            ],
        ),
        migrations.AlterField(
            model_name='relationship',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gives_friendship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_friendship', to=settings.AUTH_USER_MODEL),
        ),
    ]
