# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_auto_20171024_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.University', verbose_name='Ville'),
        ),
    ]
