# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-27 13:01
from __future__ import unicode_literals

import blousebrothers.confs.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [('cards', '0001_initial'), ('cards', '0002_auto_20170719_0831'), ('cards', '0003_auto_20170725_0926'), ('cards', '0004_card_public'), ('cards', '0005_auto_20170727_1257')]

    initial = True

    dependencies = [
        ('confs', '0050_auto_20170712_1345'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=256, verbose_name='Chapitre')),
                ('title', models.CharField(max_length=256, verbose_name='Titre du cours')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Contenu')),
                ('slug', blousebrothers.confs.models.AutoSlugField(editable=False, max_length=256, populate_from='content', unique=True, verbose_name='Slug')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cards', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('items', models.ManyToManyField(blank=True, related_name='cards', to='confs.Item', verbose_name='Items')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childs', to='cards.Card', verbose_name='Original')),
                ('specialities', models.ManyToManyField(blank=True, related_name='cards', to='confs.Speciality', verbose_name='Specialities')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.PositiveIntegerField(default=1, verbose_name='Difficulté')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck', to='cards.Card', verbose_name='Fiche')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
                ('created', models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 7, 19, 8, 30, 58, 734882, tzinfo=utc))),
                ('modified', models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 7, 19, 8, 31, 11, 321434, tzinfo=utc))),
                ('nb_views', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=blousebrothers.confs.models.AutoSlugField(editable=False, max_length=256, populate_from='title', unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='card',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 7, 25, 9, 26, 29, 573069, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cards.Card', verbose_name='Original'),
        ),
        migrations.AddField(
            model_name='card',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='card',
            name='level',
            field=models.CharField(choices=[('EASY', 'Facile'), ('MIDDLE', 'Moyen'), ('HARD', 'Dur')], default='DP', max_length=10, verbose_name='Level'),
        ),
    ]
