# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-21 08:39
from __future__ import unicode_literals

import blousebrothers.confs.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('confs', '0050_auto_20170821_0838'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Réponse')),
                ('slug', blousebrothers.confs.models.AutoSlugField(max_length=256, unique=True, verbose_name='Slug')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=False)),
                ('free', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cards', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('items', models.ManyToManyField(blank=True, related_name='cards', to='confs.Item', verbose_name='Items')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cards.Card', verbose_name='Original')),
                ('specialities', models.ManyToManyField(blank=True, related_name='cards', to='confs.Speciality', verbose_name='Specialities')),
            ],
        ),
        migrations.CreateModel(
            name='CardsPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_duration', models.DurationField(choices=[(datetime.timedelta(0, 600), '10 min'), (datetime.timedelta(0, 1200), '20 min'), (datetime.timedelta(0, 2700), '45 min')], default=datetime.timedelta(0, 600), max_length=10, verbose_name='Niveau')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_preference', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.PositiveIntegerField(choices=[(0, 'Facile'), (1, 'Moyen'), (2, 'Dur')], default=1, verbose_name='Difficulté')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('column', models.PositiveIntegerField(default=0)),
                ('wake_up', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nb_views', models.IntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck', to='cards.Card', verbose_name='Fiche')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date created')),
                ('date_modified', models.DateField(auto_now=True, verbose_name='Date modified')),
                ('selected_duration', models.DurationField()),
                ('effective_duration', models.DurationField(default=datetime.timedelta(0))),
                ('finished', models.BooleanField(default=False)),
                ('cards', models.ManyToManyField(blank=True, related_name='sessions', to='cards.Card', verbose_name='Fiches')),
                ('items', models.ManyToManyField(blank=True, related_name='sessions', to='confs.Item', verbose_name='Items')),
                ('specialities', models.ManyToManyField(blank=True, related_name='sessions', to='confs.Speciality', verbose_name='Specialities')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='cards.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cards', to='cards.Tag', verbose_name='Tags'),
        ),
    ]
