# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-19 08:31
from __future__ import unicode_literals

import blousebrothers.confs.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 7, 19, 8, 30, 58, 734882, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 7, 19, 8, 31, 11, 321434, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='nb_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=blousebrothers.confs.models.AutoSlugField(editable=False, max_length=256, populate_from='title', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck', to='cards.Card', verbose_name='Fiche'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant'),
        ),
    ]
