# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-27 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_squashed_0005_auto_20170727_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
