# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-01 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_squashed_0005_auto_20170727_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Tags')),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='section',
        ),
        migrations.RemoveField(
            model_name='card',
            name='title',
        ),
        migrations.AlterField(
            model_name='card',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Réponse'),
        ),
        migrations.AlterField(
            model_name='card',
            name='level',
            field=models.CharField(choices=[('EASY', 'Facile'), ('MIDDLE', 'Moyen'), ('HARD', 'Dur')], default='MIDDLE', max_length=10, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cards', to='cards.Tag', verbose_name='Tags'),
        ),
    ]
