# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-08 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20170727_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='level',
            field=models.CharField(choices=[('EASY', 'Facile'), ('MIDDLE', 'Moyen'), ('HARD', 'Dur')], default='MIDDLE', max_length=10, verbose_name='Level'),
        ),
    ]
