# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-25 09:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20170719_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 7, 25, 9, 26, 29, 573069, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cards.Card', verbose_name='Original'),
        ),
    ]
