# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-08 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20170808_0852'),
        ('cards', '0002_auto_20170801_1347'),
    ]

    operations = [
    ]
