# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-22 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_session_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
    ]
