# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-27 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='card',
            name='level',
            field=models.CharField(choices=[('EASY', 'Facile'), ('MIDDLE', 'Moyen'), ('HARD', 'Dur')], default='DP', max_length=10, verbose_name='Level'),
        ),
    ]
