# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-16 15:36
from __future__ import unicode_literals

import blousebrothers.confs.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('confs', '0058_auto_20170816_1536'),
        ('cards', '0004_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardsPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_duration', models.DurationField(choices=[(datetime.timedelta(0, 600), '10 min'), (datetime.timedelta(0, 1200), '20 min'), (datetime.timedelta(0, 2700), '45 min')], default=datetime.timedelta(0, 600), max_length=10, verbose_name='Niveau')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_preference', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date created')),
                ('date_modified', models.DateField(auto_now=True, verbose_name='Date modified')),
                ('selected_duration', models.DurationField()),
                ('effective_duration', models.DurationField(default=datetime.timedelta(0))),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=blousebrothers.confs.models.AutoSlugField(max_length=256, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='session',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='cards.Card', verbose_name='Fiches'),
        ),
        migrations.AddField(
            model_name='session',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='confs.Item', verbose_name='Items'),
        ),
        migrations.AddField(
            model_name='session',
            name='specialities',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='confs.Speciality', verbose_name='Specialities'),
        ),
        migrations.AddField(
            model_name='session',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant'),
        ),
        migrations.AddField(
            model_name='session',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='cards.Tag', verbose_name='Tags'),
        ),
    ]
