# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-18 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20170817_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='level',
        ),
        migrations.AlterField(
            model_name='deck',
            name='difficulty',
            field=models.PositiveIntegerField(choices=[(0, 'Facile'), (1, 'Moyen'), (2, 'Dur')], default=1, verbose_name='Difficulté'),
        ),
    ]
