# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-08 09:51
from __future__ import unicode_literals

import blousebrothers.cards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0005_remove_card_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnkiImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', image_cropping.fields.ImageCropField(max_length=255, upload_to=blousebrothers.cards.models.anki_image_directory_path, verbose_name='Image')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
            ],
        ),
        migrations.CreateModel(
            name='AnkiPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date created')),
                ('file', models.FileField(upload_to=blousebrothers.cards.models.apkg_directory_path, verbose_name='Fichier')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anki_packages', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='anki_id',
            field=models.BigIntegerField(default=None, null=True, verbose_name='id in anki package'),
        ),
        migrations.AddField(
            model_name='ankiimage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cards.AnkiPackage', verbose_name='Package'),
        ),
        migrations.AddField(
            model_name='card',
            name='anki_pkg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='cards.AnkiPackage', verbose_name='Package Anki'),
        ),
    ]
