# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-16 13:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20170816_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='nb_cards',
        ),
        migrations.AlterField(
            model_name='session',
            name='effective_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
