# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-18 15:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20170818_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='column',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deck',
            name='wake_up',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
