# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-19 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_fix_apprendre_iecn_anki'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
    ]
