# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-13 08:23
from __future__ import unicode_literals

import blousebrothers.cards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0009_private_ophtalmo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', image_cropping.fields.ImageCropField(max_length=255, upload_to=blousebrothers.cards.models.card_image_directory_path, verbose_name='Image')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_images', to=settings.AUTH_USER_MODEL, verbose_name='Image')),
            ],
        ),
    ]
