# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-17 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='search',
            field=models.TextField(blank=True, null=True, verbose_name='Rechercher'),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '430x360', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
